src/Entity/Document.php
<?php

namespace App\Entity;

use App\Repository\DocumentRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=DocumentRepository::class)
 */
class Document
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $intitule;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $type;

    /**
     * @ORM\ManyToOne(targetEntity=Repertoire::class, inversedBy="documents")
     * @ORM\JoinColumn(nullable=true)
     */
    private $Repertoire;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_creation;

    

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="Document")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $chemin;

    /**
     * @ORM\Column(type="float")
     */
    private $taille;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getIntitule(): ?string
    {
        return $this->intitule;
    }

    public function setIntitule(string $intitule): self
    {
        $this->intitule = $intitule;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(string $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getRepertoire(): ?Repertoire
    {
        return $this->Repertoire;
    }

    public function setRepertoire(?Repertoire $Repertoire): self
    {
        $this->Repertoire = $Repertoire;

        return $this;
    }

    public function getDateCreation(): ?\DateTimeInterface
    {
        return $this->date_creation;
    }

    public function setDateCreation(\DateTimeInterface $date_creation): self
    {
        $this->date_creation = $date_creation;

        return $this;
    }


    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getChemin(): ?string
    {
        return $this->chemin;
    }

    public function setChemin(string $chemin): self
    {
        $this->chemin = $chemin;

        return $this;
    }

    public function getTaille(): ?float
    {
        return $this->taille;
    }

    public function setTaille(float $taille): self
    {
        $this->taille = $taille;

        return $this;
    }
}

src/Form/DocumentType.php
<?php

namespace App\Form;

use App\Entity\Document;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class DocumentType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('intitule')
            ->add('chemin' ,FileType::class )
            ->add('Repertoire')
         
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Document::class,
        ]);
    }
}

src/Controller/DocumentController.php
<?php

namespace App\Controller;
use \Datetime;
use App\Entity\Document;
use App\Entity\Repertoire;
use App\Form\DocumentType;
use App\Repository\DocumentRepository;
use App\Repository\RepertoireRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\File\Exception\FileException;


/**
 * @Route("/document")
 */
class DocumentController extends AbstractController
{
    /**
     * @Route("/", name="app_document_index", methods={"GET"})
     */
    public function index(DocumentRepository $documentRepository): Response
    {       
        $user = $this->get('security.token_storage')->getToken()->getUser();
        return $this->render('document/index.html.twig', [
            'documents' =>$user->getDocument(),
            'repertoires' => $user->getRepertoire(),
        ]);
    }

    /**
     * @Route("/newdoc", name="sub_document", methods={"GET", "POST"})
     */
    public function subfile(RepertoireRepository $rpertoire,Request $request, DocumentRepository $documentRepository): Response
    {$user = $this->get('security.token_storage')->getToken()->getUser();
        $document = new Document();
        $currentDate = new DateTime();

        // $form = $this->createForm(DocumentType::class, $document);
        // $form->handleRequest($request);
            
        $parent = $rpertoire->find($request->request->get('parent'));
            $document->setUser($user); // set user
            $uploads_directory = $this->getParameter('targetDirectory');
            $target = $uploads_directory . basename($_FILES['Upfile']['name']);
            $document->setType($_FILES["Upfile"]["type"]);
            $document->setChemin(basename($_FILES["Upfile"]["name"]));
            $document->setIntitule($request->request->get('nnfile' , ''));
            $document->setTaille($_FILES["Upfile"]["size"]);
            $document->setDateCreation($currentDate);
            $document->setRepertoire($parent);

            try {

                move_uploaded_file($_FILES["Upfile"]["tmp_name"] , $target );
                        }catch(FileException $e){               

            }
            $documentRepository->add($document, true);
            return $this->redirectToRoute('base', [], Response::HTTP_SEE_OTHER);

       
    }
    /**
     * @Route("/new", name="app_document_new", methods={"GET", "POST"})
     */
    public function new(Request $request, DocumentRepository $documentRepository): Response
    {$user = $this->get('security.token_storage')->getToken()->getUser();
        $document = new Document();
        $currentDate = new DateTime();

  

       
        // $form = $this->createForm(DocumentType::class, $document);
        // $form->handleRequest($request);
            
      
        $document->setUser($user); // set user
        //  $fish =$form['chemin']->getData();
        $uploads_directory = $this->getParameter('targetDirectory');
        $target = $uploads_directory . basename($_FILES['Upfile']['name']);
        $document->setType($_FILES["Upfile"]["type"]);
        $document->setChemin(basename($_FILES["Upfile"]["name"]));
        $document->setIntitule($request->request->get('fileN' , ''));
        $document->setTaille($_FILES["Upfile"]["size"]);
        $document->setDateCreation($currentDate);

        try {

            move_uploaded_file($_FILES["Upfile"]["tmp_name"] , $target );
                    }catch(FileException $e){               

        }
        $documentRepository->add($document, true);
        return $this->redirectToRoute('base', [], Response::HTTP_SEE_OTHER);

       
    }

    /**
     * @Route("/{id}", name="app_document_show", methods={"GET"})
     */
    public function show(Document $document): Response
    {
        return $this->render('document/show.html.twig', [
            'document' => $document,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="app_document_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, Document $document, DocumentRepository $documentRepository , RepertoireRepository $repertoireRepository): Response
    {
        // $form = $this->createForm(DocumentType::class, $document);
        // $form->handleRequest($request);
    
       $uploads_directory = $this->getParameter('targetDirectory');
       if($_FILES['load']['name']){
              $oldlink = $uploads_directory . $document->getChemin();
              unlink($oldlink);
        $document->setType($_FILES["load"]["type"]);
        $document->setChemin(basename($_FILES["load"]["name"]));
        $document->setTaille($_FILES["load"]["size"]);
        
        $target = $uploads_directory . basename($_FILES['load']['name']);
        try {

            move_uploaded_file($_FILES["load"]["tmp_name"] , $target );
                    }catch(FileException $e){               

        }
    }
    $parent = $repertoireRepository->findOneBySomeField($request->request->get('alter_parent'));
    $document->setRepertoire($parent);
    $document->setIntitule($request->request->get('altered_name'));
            $documentRepository->add($document, true);

        

            return $this->redirectToRoute('base', [], Response::HTTP_SEE_OTHER);

    }

    

    /**
     * @Route("/{id}", name="app_document_delete", methods={"POST"})
     */
    public function delete(Request $request, Document $document, DocumentRepository $documentRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$document->getId(), $request->request->get('_token'))) {
            $uploads_directory = $this->getParameter('targetDirectory');
            unlink($uploads_directory .'/' . $document->getChemin() );
            $documentRepository->remove($document, true);

        }

        return $this->redirectToRoute('base', [], Response::HTTP_SEE_OTHER);
    }
}

templates/document/_delete_form.html.twig
<form method="post" action="{{ path('app_document_delete', {'id': document.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ document.id) }}">
    <button class="btn">Delete</button>
</form>

templates/document/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/document/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Document{% endblock %}

{% block body %}
    <h1>Edit Document</h1>

    {{ include('document/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_document_index') }}">back to list</a>

    {{ include('document/_delete_form.html.twig') }}
{% endblock %}

templates/document/index.html.twig
{% extends 'base.html.twig' %}
{% import 'macros/macro.html.twig' as macro %}

{% block title %}Document index{% endblock %}
{% block body %}
  <div class="content-page">
        <div class="container-fluid">
            <div class="row">
         
        <tbody>
        <div class="card card-block card-stretch card-height files-table">                   
                        <div class="card-header d-flex justify-content-between">
                            <div class="header-title">
                                <h4 class="card-title">Files</h4>
                                
                            </div>
                            
                        </div>
                        <div class="card-body pt-0">
                            <div class="table-responsive">
                                <table class="table mb-0 table-borderless tbl-server-info">
                                <thead>
                                    <tr>
                                        <th scope="col">Name</th>
                                        <th scope="col">Type</th>
                                        <th scope="col">Size</th>
                                        <th scope="col">Creation Date</th>
                                        <th scope="col"></th>
                                    </tr>
                                </thead>

                                
                                <tbody>
                                   
                                    
                             {% for file in documents %}
  {{ macro.edit_modal( path('app_document_edit', {'id':file.id, }) , repertoires ) }}
                                 
                                
                                    <tr>
                                       <td>
                                            <div class="d-flex align-items-center">
                                            {# make a switch statment for file icon rendering #}
                                                <div    data-load-file="file" data-load-target="#resolte-contaniner" data-url="{{ asset( 'uploads/'~file.chemin~'' ) }}" data-toggle="modal" data-target="#exampleModal" data-title="{{file.chemin}}" style="cursor: pointer;">
                                              
                                              {% if 'image' in file.type %}
                                              <div class="icon-small bg-light rounded mr-3">
                                                   <i class="la la-file-image-o"></i>
                                                   </div>
                                              {% elseif 'pdf' in file.type %}
                                                  <img src = "{{asset("assets/images/layouts/page-1/pdf.png")}}"class="img-fluid" alt="image1" width = "38">
                                              {% elseif 'xls' in file.type %}
                                                  <img src = "{{asset("assets/images/layouts/page-1/xlsx.png")}}"class="img-fluid" alt="image1" width = "38">
                                              
                                              {% elseif 'ppt' in file.type %}
                                                  <img src = "{{asset("assets/images/layouts/page-1/ppt.png")}}"class="img-fluid" alt="image1" width = "38">
                                              {% else %}
                                                
                                                  <img src = "{{asset("assets/images/layouts/page-1/doc.png")}}"class="img-fluid" alt="image1" width = "38">
                                              
                                              {% endif %}
                                              
                                              


                                                  
                                                </div>
                                               
                                             <div data-load-file="file" data-load-target="#resolte-contaniner" data-url="{{ asset( 'uploads/'~file.chemin~'' ) }}" data-toggle="modal" data-target="#exampleModal" data-title="{{file.chemin}}" style="cursor: pointer;">{{ file.intitule}}</div>
                                              {# {{ macro.small_edit( path('quick', {'id':file.id, })  ) }} #}

                                            </div>
                                        </td>
                                                 <td>{{file.type}}</td>
                                         {% if file.taille > 100000 %} 

                                        <td>{{ (file.taille / 1000000 )|number_format }} MB</td>
                                        {% else %}
                                        <td>{{ (file.taille / 1000)|number_format }} KB</td>


                                        {% endif %}
                                        <td>{{ file.dateCreation ? file.dateCreation|date('H:i | Y/m/d') : '' }}</td>
                                        {# quick if stt for the size  #}
                                        


                                        <td>
                                            <div class="dropdown">
                                                <span class="dropdown-toggle" id="dropdownMenuButton9" data-toggle="dropdown">
                                                    <i class="ri-more-fill"></i>
                                                </span>
                                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton9">
                                                    <a class="dropdown-item" href="{{ asset( 'uploads/'~file.chemin~'' ) }}"><i class="ri-eye-fill mr-2"></i>View</a>
                                                    {# need to figure out a way to update the last-modifed-time attribute  #} 
                                        <form method="post" action="{{ path('app_document_delete', {'id': file.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
                                        <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ file.id) }}">
                                            <button class="dropdown-item" style="font-size : 19px" ><i class="ri-delete-bin-6-fill mr-2"></i>Delete</button>
                                            </form>




                                                    <a class="dropdown-item"  data-toggle="modal" data-target="#alterfile"  href="#"><i class="ri-pencil-fill mr-2"></i>Edit</a>
                               

                                                               <a class="dropdown-item"  href="{{ asset( 'uploads/'~file.chemin~'' ) }}"><i class="ri-file-download-fill mr-2"></i>Download</a>
                                                </div>
                                            </div>
                                        </td>
                                    </tr>




                        {% endfor %}

                                </tbody>


                                
                                </table>
                            </div>
                        </div>
                    </div>
                
          
        </tbody>

        </div>
    </div>
 </div>
{% endblock %}

templates/document/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Document{% endblock %}

{% block body %}
    <h1>Create new Document</h1>

    {{ include('document/_form.html.twig') }}

    <a href="{{ path('app_document_index') }}">back to list</a>
{% endblock %}

templates/document/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Document{% endblock %}

{% block body %}
    <h1>Document</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ document.id }}</td>
            </tr>
            <tr>
                <th>Intitule</th>
                <td>{{ document.intitule }}</td>
            </tr>
            <tr>
                <th>Type</th>
                <td>{{ document.type }}</td>
            </tr>
            <tr>
                <th>Date_creation</th>
                <td>{{ document.dateCreation ? document.dateCreation|date('Y-m-d') : '' }}</td>
            </tr>
           
            <tr>
                <th>Chemin</th>
                <td>{{ document.chemin }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_document_index') }}">back to list</a>

    <a href="{{ path('app_document_edit', {'id': document.id}) }}">edit</a>

    {{ include('document/_delete_form.html.twig') }}
{% endblock %}